sudo: true
language: node_js
node_js:
  - v6
  - v4
cache:
  directories:
    - node_modules
before_script:
  - npm i
script:
  - npm test
after_success:
- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
