language: node_js

node_js:
  - node
  - 6
  - 4

cache:
  directories:
    - node_modules

after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
