language: node_js

node_js:
  - node
  - 6
  - 4

cache:
  directories:
    - node_modules

after_success:
- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

notifications:
  email: false
