language: node_js
node_js:
  - node
  - lts/*
  - 10

after_success:
  - npm i coveralls
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

notifications:
  email: false
